### ISSUE TITLE
about the port which  the wordpress docker image listens: 9000?

### ISSUE THREAD

**Issue by scil** [gregmsanderson/fly-hello-wordpress#3]
the comment in `fly.toml` :
```
 the default WordPress image listens on port 80, rather than the more common 8080
```

today I use the latest docker image `FROM wordpress:6-php8.2-fpm-alpine` and run `fly deploy` and  found that 
```
WARNING The app is not listening on the expected address and will not be reachable by fly-proxy.
You can fix this by configuring your app to listen on the following addresses:
  - 0.0.0.0:80
Found these processes inside the machine with open listening sockets:
  PROCESS                                               | ADDRESSES
--------------------------------------------------------*---------------------------------------
  php-fpm: master process (/usr/local/etc/php-fpm.conf) | [::]:9000
  /.fly/hallpass                                        | [fdaa:2:cf76:a7b:18b:a017:8944:2]:22
  php-fpm: pool www                                     | [::]:9000
  php-fpm: pool www                                     | [::]:9000

```

I change  `  internal_port = 80` to `  internal_port = 9000` and everything went well.

the 9000 the the php-fpm listens at,  not the apache.

**Comment by scil** [comment]
I found that my choice of `wordpress:6-php8.2-fpm-alpine` is not fine, because this image have only php-fpm but lack of a http sever.

now I use `FROM wordpress:6.3-php8.2-apache` and keep the ` internal_port = 80`

**Comment by gregmsanderson** [comment]
Thanks for the update.

Yep, as you say there are different images depending what you need. For both a web server _and_ PHP-FPM you would need an image with e.g apache or nginx. I know the default WordPress image does and uses port 80, so it sounds like that's still the case.
